### ISSUE TITLE
⚡ Release v4.0.0-alpha.1

### ISSUE THREAD

**Issue by in4s** [in4s/bem#34]
- [x] Pin this issue; Pin it to the left
- [x] ** Update RSR (optional)
- [ ] ** if the branch 4.0 does not exist
    - [ ] git checkout PREVIEWS_BRANCH_NAME
    - [ ] git pull
    - [ ] create the branch 4.0
    - [ ] git checkout the branch 4.0
    - [ ] git push
- [ ] git checkout the branch 4.0
- [x] git pull
- [x] git checkout -b Release_v4.0.0-alpha.1_#34
- [x] ** Run and check Unit Tests of this library
- [x] Fix the current version number in files:
    - [x] In README.md
    - [x] In composer.json
- [x] git add . , git commit -m "⚡ Release v4.0.0-alpha.1 close #34"
- [x] (C*rmr) Create pull request "⚡ Release v4.0.0-alpha.1 close #34"
------
- [x] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [x] click and save https://github.com/in4s/bem/releases/new?tag=v4.0.0-alpha.1&target=4.0
- [x] Increase the version number in local data.js
- [x] Remove local branch
- [x] click and save https://github.com/in4s/bem/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v4.0.0-alpha.1+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [x] Pin this test issue; Pin it to the left
- [x] Close milestone with current version name
- [x] Unpin this issue
