### ISSUE TITLE
⚡ Release v3.0.0-alpha.4

### ISSUE THREAD

**Issue by in4s** [in4s/bem#50]
- [ ] ** Update RSR (optional)
- [x] git checkout the branch 3.0
- [x] git pull
- [x] git checkout -b Release_v3.0.0-alpha.4_#50
- [x] ** check PSR by running php-cs-fixer
    - [x] php-cs-fixer fix .
    - [ ] if files was changed
        - [ ] git add .
        - [ ] git commit -m "php-cs-fixed"
- [x] Fix the current version number in files:
    - [x] In README.md
    - [x] In composer.json
- [x] git add . , git commit -m "⚡ Release v3.0.0-alpha.4 close #50"
- [x] (C*rmr) By process IV Create pull request "⚡ Release v3.0.0-alpha.4 close #50"
------
- [x] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [x] click and save https://github.com/in4s/bem/releases/new?tag=v3.0.0-alpha.4&target=3.0
- [ ] Increase the version number in local data.js
- [x] Remove local branch
- [x] click and save https://github.com/in4s/bem/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v3.0.0-alpha.4+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [x] Pin this test issue; Pin it to the left
- [x] Close milestone with current version name
- [x] Unpin this issue
