### ISSUE TITLE
⚡ Release v3.0.0

### ISSUE THREAD

**Issue by in4s** [in4s/bem#53]
- [ ] ** Update RSR (optional)
- [ ] ** if the branch 3.0 does not exist
    - [ ] git checkout PREVIEWS_BRANCH_NAME
    - [ ] git pull
    - [ ] create the branch 3.0
    - [ ] git checkout the branch 3.0
    - [ ] git push
    - [ ] !!! If the branch has the highest number, set it as the default branch on [Github](https://github.com/in4s/bem/settings/branches)
- [x] git checkout the branch 3.0
- [x] git pull
- [x] git checkout -b Release_v3.0.0_#53
- [x] Fix the current version number in files:
    - [x] In README.md
    - [x] In composer.json
- [x] git add . , git commit -m "⚡ Release v3.0.0 close #53"
- [x] (C*rmr) By process IV Create pull request "⚡ Release v3.0.0 close #53"
------
- [x] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [x] click and save https://github.com/in4s/bem/releases/new?tag=v3.0.0&target=3.0
- [ ] Increase the version number in local data.js
- [x] Remove local branch
- [ ] click and save https://github.com/in4s/bem/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v3.0.0+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [ ] Pin this test issue; Pin it to the left
- [x] Close milestone with current version name
- [x] Unpin this issue
