### ISSUE TITLE
⚡ Release v4.0.0

### ISSUE THREAD

**Issue by in4s** [in4s/bem#62]
- [x] ** Update RSR (optional)
- [x] git checkout the branch main
- [x] git pull
- [x] git checkout -b Release_v4.0.0_#62
- [x] Fix the current version number in files:
    - [x] In README.md
    - [x] In composer.json
- [x] git add . , git commit -m "⚡ Release v4.0.0 close #62"
- [ ] (C*rmr) By process IV Create pull request "⚡ Release v4.0.0 close #62"
------
- [ ] !!!!!!!!!!!!!!!!!!!!!! (cRM*R) Review pull request, Merge it, !!!!!!!!!!!!!! swapping title and description, Remove remote branch
- [ ] click and save https://github.com/in4s/bem/releases/new?tag=v4.0.0&target=main
- [ ] Increase the version number in local data.js
- [ ] Remove local branch
- [ ] click and save https://github.com/in4s/bem/issues/new/?assignees=in4s&labels=test,canProceed,Urgent&title=☑+v4.0.0+on+m&body=-+%5B+%5D+Pin+this+issue%3B+Pin+it+to+the+left%0D%0A-+%5B+%5D+Run+the+test+and+complete+it%0D%0A-+%5B+%5D+Unpin+this+issue+after+closing+it
- [ ] Pin this test issue; Pin it to the left
- [ ] Close milestone with current version name
- [ ] Unpin this issue
